# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Documents/Vivado/GOD/GOD.srcs/sources_1/ip/axi_interconnect/axi_interconnect.xci
# IP: The module: 'axi_interconnect' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/Vivado/GOD/GOD.srcs/sources_1/ip/axi_interconnect/axi_interconnect_impl_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_interconnect'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Documents/Vivado/GOD/GOD.srcs/sources_1/ip/axi_interconnect/axi_interconnect_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_interconnect'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Documents/Vivado/GOD/GOD.srcs/sources_1/ip/axi_interconnect/axi_interconnect_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_interconnect'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Documents/Vivado/GOD/GOD.srcs/sources_1/ip/axi_interconnect/axi_interconnect.xci
# IP: The module: 'axi_interconnect' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/Vivado/GOD/GOD.srcs/sources_1/ip/axi_interconnect/axi_interconnect_impl_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_interconnect'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Documents/Vivado/GOD/GOD.srcs/sources_1/ip/axi_interconnect/axi_interconnect_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_interconnect'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Documents/Vivado/GOD/GOD.srcs/sources_1/ip/axi_interconnect/axi_interconnect_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_interconnect'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
