# Generated by Django 3.0.3 on 2020-04-19 04:21

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetWorkSpeedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_speed', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='upload_speed')),
                ('download_speed', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='download_speed')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 4, 19, 4, 21, 15, 739871, tzinfo=utc), verbose_name='date')),
            ],
            options={
                'db_table': 'network_speed',
            },
        ),
    ]
