# Generated by Django 3.0.3 on 2020-04-19 04:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network_speed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkspeedmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 4, 21, 44, 638971, tzinfo=utc), verbose_name='date'),
        ),
    ]
