# Generated by Django 3.0.3 on 2020-04-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_speed', '0002_auto_20200419_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkspeedmodel',
            name='date',
            field=models.DateTimeField(verbose_name='date'),
        ),
    ]
