# Generated by Django 3.0.3 on 2020-04-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_speed', '0003_auto_20200419_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkspeedmodel',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='description'),
        ),
    ]
